name:                FULE
version:             0.3.1
github:              "pschnapp/FULE"
license:             BSD3
author:              "Paul Schnapp"
maintainer:          "paul.schnapp@gmail.com"
copyright:           "2022-2024 Paul Schnapp"

extra-source-files:
- README.md
- CHANGELOG.md
- doc/Theory.md
- doc/Usage.md

# Metadata used when publishing your package
synopsis:            Functional UI Layout Engine
category:            GUI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pschnapp/FULE#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.5 && < 0.7
- deepseq >= 1.4.6 && < 1.5
- mtl >= 2.2.2 && < 2.4
- transformers >= 0.5.6 && < 0.7

ghc-options:
  #- -Wall
  #- -Wcompat
  #- -Widentities
  #- -Wincomplete-record-updates
  #- -Wincomplete-uni-patterns
  #- -Wmissing-export-lists
  #- -Wmissing-home-modules
  #- -Wpartial-fields
  - -Wredundant-constraints

library:
  ghc-options:
  - -Wunused-packages
  source-dirs: src

tests:
  FULE-test:
    main:                Spec.hs
    source-dirs:         [examples, test]
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FULE
